name: do_dart
description: Dongkap | Mobile Application Framework with Flutter (Android & iOS).
publish_to: 'none'
version: 1.0.0+1
homepage: https://github.com/ridlafadilah/do-dart
repository: https://github.com/ridlafadilah/do-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1
  smooth_star_rating: ^1.1.1
  flutter_launcher_icons: ^0.8.1
  package_info: ^0.4.3+2
  cached_network_image: ^2.3.3
  encrypt: ^4.1.0
  do_core:
    path: packages/do_core
  do_common:
    path: packages/do_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.4
  bloc_test: ^7.1.0
  mockito: ^4.1.3
  json_serializable: ^3.5.0
  build_runner: ^1.10.4
  retrofit_generator: ^1.4.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  adaptive_icon_background: "#FFF"
  adaptive_icon_padding: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/avatars/
    - assets/eva_icons/fill/svg/
    - assets/eva_icons/outline/svg/
    - assets/flags/
    - assets/images/
    - assets/uitemplate/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
