name: Dongkap Analyzer

on:
  push:
    branches: [ main ]

jobs:
  package-analysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: axel-op/dart-package-analyzer@v2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: do_dart/
